spring.application.name=ecom_application
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5433/user_service
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
