ALTER TABLE users ADD COLUMN email VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN role  VARCHAR(50)  NOT NULL DEFAULT 'USER';

ALTER TABLE users ALTER COLUMN email DROP DEFAULT;
ALTER TABLE users ADD CONSTRAINT users_email_unique UNIQUE (email);
